# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, default='book.png', upload_to='book_images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookorderinstance',
            name='is_returned',
            field=models.BooleanField(default=False, help_text='Mark a book as returned'),
        ),
        migrations.AddField(
            model_name='bookorderinstance',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_books', to='catalog.Author'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select genre for this book', related_name='genre_books', to='catalog.Genre'),
        ),
    ]
