# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161110_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('e', 'E-book'), ('p', 'Paperback'), ('a', 'Audio Book'), ('h', 'Hardback')], default='p', help_text='Book Type such as e-book/paperback?', max_length=1),
        ),
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(default='', help_text='Enter an email address for the borrower', max_length=254),
        ),
    ]
