# Generated by Django 2.1.4 on 2019-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20161110_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Availability status of a book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Enter a book genre', max_length=140),
        ),
    ]
