# Generated by Django 2.1.4 on 2019-01-12 10:16

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190111_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorderinstance',
            options={'verbose_name_plural': 'Book Orders'},
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='book_images/book.png', upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, editable=False, help_text='Availability status of a book'),
        ),
        migrations.AlterField(
            model_name='bookorderinstance',
            name='book',
            field=models.ForeignKey(help_text='Enter book to be lent out', limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.CASCADE, to='catalog.Book'),
        ),
        migrations.AlterField(
            model_name='bookorderinstance',
            name='due_date',
            field=models.DateField(blank=True, default=catalog.models.BookOrderInstance.default_due_date, editable=False),
        ),
        migrations.AlterField(
            model_name='bookorderinstance',
            name='return_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
